Dummy json
Caleb-Cohen/Together pull request #68
Opened 2022-11-17 05:35 UTC by Caleb-Cohen

# Description

Merges @JoeDravarol and @code2244 work of creating a JSON Dummy Server into add-event-form

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2022-11-17 05:36 UTC, Caleb-Cohen commented
@InstincDev and @MatthewBozin please review to complete the merge.

2022-11-17 18:43 UTC, JoeDravarol requested changes

2022-11-17 18:43 UTC, JoeDravarol commented on frontend/src/services/events.js
> +        id: uuidv4()
The uuid package can be removed. It turns out json-server will generate the id for us.

2022-11-17 18:43 UTC, JoeDravarol commented on frontend/src/services/events.js
> +import { v4 as uuidv4 } from 'uuid';
Remove uuid here.

2022-11-17 18:43 UTC, JoeDravarol commented on frontend/package.json
> +    "uuid": "^9.0.0"
Remove uuid here.

2022-11-17 18:47 UTC, Caleb-Cohen commented
@JoeDravarol, check the commits for your requests.

2022-11-17 19:47 UTC, JoeDravarol commented on frontend/src/services/events.js
> +    })
@Caleb-Cohen That looks good. Just a minor nitpick. You can do this instead:

```suggestion
const response = await axios.post('http://localhost:2121/events', userData)
```

2022-11-18 00:53 UTC, InstincDev commented
This looks clean and good to go.

2022-11-18 16:50 UTC, merged